version: "2"
services:
  zookeeper1:
    image: elevy/zookeeper:latest
    container_name: zookeeper1
    environment:
      MYID: 1
      SERVERS: zookeeper1,zookeeper2,zookeeper3
    ports:
      - "2181:2181"
      - "2888"
      - "3888"

  zookeeper2:
    image: elevy/zookeeper:latest
    container_name: zookeeper2
    environment:
      MYID: 2
      SERVERS: zookeeper1,zookeeper2,zookeeper3
    ports:
      - "2182:2181"
      - "2888"
      - "3888"

  zookeeper3:
    image: elevy/zookeeper:latest
    container_name: zookeeper3
    environment:
      MYID: 3
      SERVERS: zookeeper1,zookeeper2,zookeeper3
    ports:
      - "2183:2181"
      - "2888"
      - "3888"

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.86.20
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_CREATE_TOPICS: hot-topic-1:1:3,hot-topic-2:1:3,hot-topic-3:1:3

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LOG_DIRS: /kafka
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_HOST_NAME: 192.168.86.20
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"

  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LOG_DIRS: /kafka
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ADVERTISED_HOST_NAME: 192.168.86.20
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
